# -*- coding: utf-8 -*-
"""Desafio_Arquitetura REST.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KkQsWDvOlRBYx-EcyT6YFz5yfDBs4gf6
"""

from pip._vendor import requests
import json
# OI
# API
response = requests.get(
    'https://www.googleapis.com/books/v1/volumes?q=software+inauthor:')
responseJSON = json.loads(response.content)
# print(responseJSON["items"][0]["volumeInfo"]['authors'][0])


def return_int(var, texto):
    var = input(texto)
    try:
        return int(var)
    except ValueError as err:  # formato errado
        print('Formato errado')
        input()
    return return_int(var, texto)  # repetir a pergunta


# DECLARAR VÁRIAVEIS
fim1 = False
fim2 = False
fim3 = False
fim4 = False
fim5 = False
acesso = int
resp1 = int
resp2 = str
resp4 = int
nomeCadLivr = str
autorCadLivr = str
dataCadLivr = int
dispCadLivr = int
nomeVeri = str
senhaVeri = int
nomeReserva = str
indexUsu = int
quantReserva = 0

Usu = {
    0: {
        "nome": "ADM",
        "senha": "0",
        "livrosEmpre": []
    },
    1: {
        "nome": "teste",
        "senha": "0",
        "livrosEmpre": []
    },
    2: {
        "nome": "",
        "senha": "0",
        "livrosEmpre": []
    },
    3: {
        "nome": "",
        "senha": "0",
        "livrosEmpre": []
    },
    4: {
        "nome": "",
        "senha": "0",
        "livrosEmpre": []
    }
}

Livros = {
    0: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 5
    },
    1: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 3
    },
    2: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 8
    },
    3: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 3
    },
    4: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 2
    },
    5: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 5
    },
    6: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 1
    },
    7: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 0
    },
    8: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 0
    },
    9: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 5
    },
    10: {
        "titulo": "",
        "ediora": 0,
        "autor": "",
        "data": 0,
        "disp": 4
    }
}
cont = 2
contLivros = 0


# LOGIN E CADASTRO
print("-------Bem vindo a Biblioteca Online-------")
while (fim1 == False):
    fim2 = False
    print("Escolha uma das opções: \n [1] Cadastro \n [2] Login \n\n")
    resp1 = input("RESPOSTA: ")
    if resp1 == "1":
        nomeCad = input("Primeiramente, informe seu nome: ")
        senhaCad = input("Agora, informe sua senha: ")
        Usu[cont].update({"nome": nomeCad})
        Usu[cont].update({"senha": senhaCad})
        cont = 1 + cont
        print(
            "Pronto, seu cadastro está pronto (aperte qualquer tecla para continuar)")
        input()
    elif resp1 == "2":
        while (fim2 != True):
            fim4 = False
            nomeVeri = input("Usuário: ")
            senhaVeri = input("Senha: ")
            for i in Usu:
                if (nomeVeri == Usu[i]["nome"] and senhaVeri == Usu[i]["senha"]):
                    indexUsu = i
                    if (nomeVeri == "ADM"):
                        acesso = 1
                    else:
                        acesso = 2
                    print("Acesso liberado para " +
                          Usu[indexUsu]["nome"] + " (pressione qualquer tecla para continuar)")
                    fim1 = True
                    fim2 = True
                    fim4 = True
                    input()
                    break
            else:
                while (fim4 != True):
                    resp2 = input(
                        "Dados não compatíveis, deseja tentar novamente? [s/n] ")
                    if (resp2 == 'n' or resp2 == 'N'):
                        fim4 = True
                        fim2 = True
                    elif (resp2 == 's' or resp2 == 'S'):
                        fim4 = True
                        # clear()
                        # Voltar para o Login
                    else:
                        print(
                            "Opção inválida (pressione qualquer tecla para continuar)")
                        input()
    else:
        print("Opção inválida (pressione qualquer tecla para continuar)")
        input()
# clear()

# INÍCIO
if (acesso == 1):  # Acesso do funcionário
    while (fim3 != True):
        print("Olá " + Usu[indexUsu]["nome"] +
              " , qual operação deseja fazer?")
        print("[1] Exibir catálogo de livros mais famosos")
        print("[2] Realizar o cadastro de um livro")
        print("[3] Sair do sistema\n")

        resp2 = input("RESPOSTA: ")

        match(resp2):
            case "1":
                # API
                for i in range(10):
                    if Livros[i]["titulo"] != "":
                        print("---------------------------------")
                        print("Livro " + str(i + 1))
                        print("\n Título: " + Livros[i]["titulo"] + "\n Editora: " + Livros[i]["editora"] + "\n Autor: " + Livros[i]
                              ["autor"] + "\n Data de lançamento: " + str(Livros[i]["data"]) + "\n Exemplares disponíveis: " + str(Livros[i]["disp"]))
                        print("---------------------------------")
                    else:
                        try:
                            print("---------------------------------")
                            print("Livro " + str(i + 1))
                            print("\n Título: " + responseJSON["items"][i]["volumeInfo"]['title'] + "\n Editora: " + responseJSON["items"][i]["volumeInfo"]['publisher'] + "\n Autor: " + responseJSON["items"]
                                  [i]["volumeInfo"]['authors'][0] + "\n Data de lançamento: " + str(responseJSON["items"][i]["volumeInfo"]['publishedDate']) + "\n Exemplares disponíveis: " + str(Livros[i]["disp"]))
                            print("---------------------------------\n")
                        except NameError as err:
                            print("---------------------------------")
                            print("Livro " + str(i + 1) + " está indisponível")
                            print("---------------------------------\n")
                print("aperte qualquer tecla para continuar")
                input()
            case "2":
                nomeCadLivr = input("Insira o nome do livro: ")
                editoraCadLivr = input("Insira o nome da editora: ")
                autorCadLivr = input("Insira o nome do autor: ")
                dataCadLivr = return_int(
                    dataCadLivr, "Insira a data de lançamento: ")
                # dataCadLivr = int(input())
                dispCadLivr = return_int(
                    dispCadLivr, "Insira quantos estão disponíveis: ")
                # dispCadLivr = int(input())

                Livros[contLivros].update({"titulo": nomeCadLivr})
                Livros[contLivros].update({"editora": editoraCadLivr})
                Livros[contLivros].update({"autor": autorCadLivr})
                Livros[contLivros].update({"data": dataCadLivr})
                Livros[contLivros].update({"disp": dispCadLivr})
                contLivros = contLivros + 1
                print(
                    "Pronto, livro cadastrado!! (pressione qualquer tecla para continuar)")
                input()
            case "3":
                # /dev/null
                fim3 = True

            case _:
                print("Opção inválida (pressione qualquer tecla para continuar)")
                input()

    print("Obrigado por usar!! (pressione qualquer tecla para continuar)")
    input()

elif (acesso == 2):  # Acesso do usuário
    while (fim3 != True):
        fim5 = False
        print("Olá " + Usu[indexUsu]["nome"] +
              " , qual operação deseja fazer?")
        print("[1] Exibir catálogo de livros mais famosos")
        print("[2] Reservar livro")
        print("[3] Conferir perfil")
        print("[4] Sair do sistema\n")

        resp2 = input("RESPOSTA: ")

        match(resp2):
            case "1":
                # API
                for i in range(10):
                    if Livros[i]["titulo"] != "":
                        print("---------------------------------")
                        print("Livro " + str(i + 1))
                        print("\n Título: " + Livros[i]["titulo"] + "\n Editora: " + Livros[i]["editora"] + "\n Autor: " + Livros[i]
                              ["autor"] + "\n Data de lançamento: " + str(Livros[i]["data"]) + "\n Exemplares disponíveis: " + str(Livros[i]["disp"]))
                        print("---------------------------------")
                    else:
                        print("---------------------------------")
                        print("Livro " + str(i + 1))
                        print("\n Título: " + responseJSON["items"][i]["volumeInfo"]['title'] + "\n Editora: " + responseJSON["items"][i]["volumeInfo"]['publisher'] + "\n Autor: " + responseJSON["items"][i]["volumeInfo"]['authors'][0] +
                              "\n Data de lançamento: " + str(responseJSON["items"][i]["volumeInfo"]['publishedDate']) + "\n Exemplares disponíveis: " + str(Livros[i]["disp"]))
                        print("---------------------------------\n")
                print("aperte qualquer tecla para continuar")
                input()
            case "2":
                print("Insira o nome do livro que deseja reservar")
                nomeReserva = str(input())
                cont2 = 0
                for i in range(10):
                    if nomeReserva == responseJSON["items"][i]["volumeInfo"]['title'] or nomeReserva == Livros[i]["titulo"]:
                        cont2 = 1
                        if Livros[i]["disp"] != 0:
                            quantReserva = quantReserva + 1
                            Usu[indexUsu]["livrosEmpre"].append(
                                nomeReserva)
                            Livros[i]["disp"] = Livros[i]["disp"] - 1
                            print(
                                "Pronto, livro reservado!! (aperte qualquer tecla para continuar)")
                            break
                        else:
                            print(
                                "Este livro não possui exemplares disponíveis (aperte qualquer tecla para continuar)")
                            break
                if (cont2 == 0):
                    print(
                        "O livro digitado não está disponível (aperte qualquer tecla para continuar)")
                    cont2 = 0
                input()
            case "3":
                while fim5 != True:
                    fim6 = False
                    print("------------Perfil----------")
                    print("\n Nome: " + Usu[indexUsu]["nome"] + "\n Senha: " +
                          str(Usu[indexUsu]["senha"]) + "\n Livros reservados: \n")
                    if quantReserva != 0:
                        for i in range(quantReserva):
                            print("    Livro " + str(i + 1) + ": " +
                                  Usu[indexUsu]["livrosEmpre"][i] + "\n")
                    else:
                        print("-sem exemplares reservados-")
                    print("----------------------------")

                    print(
                        "Como deseja prosseguir? \n [1]Renovar o tempo de algum empréstimo \n (Ou aperte qualquer outra tecla para voltar ao menu)\n")
                    resp3 = input("RESPOSTA: ")
                    if (resp3 == "1"):
                        if quantReserva != 0:
                            while fim6 != True:
                                fim7 = False
                                for i in range(quantReserva):
                                    print("    Livro " + str(i + 1) + ": " +
                                          Usu[indexUsu]["livrosEmpre"][i] + "\n")
                                # resp4 = int(input("Qual deseja renovar o empréstimo? (insira o número correspondente ao livro) "))
                                resp4 = return_int(
                                    resp4, "Qual deseja renovar o empréstimo? (insira o número correspondente ao livro) ")
                                if (Usu[indexUsu]["livrosEmpre"][resp4 - 1] != ""):
                                    # adcionar tempo no livro
                                    print(
                                        "Pronto, livro adcionado! (aperte qualquer tecla para continuar)")
                                    fim6 = True
                                else:
                                    while (fim7 != True):
                                        resp5 = input(
                                            "Livro inválido, deseja tentar novamente? [s/n]")
                                        if (resp5 == 's' or resp5 == 'S'):
                                            fim7 = True
                                            print("\n")
                                        elif (resp5 == 'n' or resp5 == 'N'):
                                            fim6 = True
                                            fim7 = True
                                        else:
                                            input(
                                                "Resposta inválida (Pressione qualquer tecla para continuar)")
                        else:
                            print(
                                "-sem exemplares reservados- \n (Aperte qualquer tecla para continuar)")
                    else:
                        fim5 = True
            case "4":
                # clear()
                fim3 = True
                break

            case _:
                print("Opção inválida (pressione qualquer tecla para continuar)")
                input()
    print("Obrigado por usar!! (pressione qualquer tecla para continuar)")
    input()